// ===== DATA QUEMADA MIENTRAS NO HAY BACKEND REAL, PARA PROBAR FUNCIONALIDADES Y DISEÑOS =====

export const FOUNDATIONS = [
    {
        id: 1,
        name: "Fundación Educativa",
        initials: "FE",
        color: "#1d4ed8",
        description:
            "Fundación Educativa trabaja desde 2010 para garantizar el acceso a educación de calidad en comunidades vulnerables de toda Argentina. Creemos que la educación es la herramienta más poderosa para transformar vidas.",
        mission:
            "Promover el derecho a la educación de niños y jóvenes en situación de vulnerabilidad.",
        vision: "Un país donde todos los niños tengan acceso a educación de calidad, sin importar su origen o situación económica.",
        category: "Educación",
        coverage: "Nacional",
        contact: "contacto@fundacioneducativa.org",
        website: "www.fundacioneducativa.org",
        social: { facebook: "#", twitter: "#", linkedin: "#" },
        beneficiaries: 2450,
        campaigns_executed: 87,
        resources: "$8.5M",
        transparency: "Alta",
        verified: true,
        activeCampaigns: 12,
        totalBeneficiaries: 5400,
        location: "Buenos Aires, Argentina",
        founded: "2010",
    },
    {
        id: 2,
        name: "ONG Agua Limpia",
        initials: "AL",
        color: "#0891b2",
        description:
            "Proveemos acceso a agua potable y saneamiento básico en comunidades rurales sin infraestructura.",
        mission: "Garantizar el acceso universal al agua potable.",
        vision: "Un mundo donde nadie muera por falta de agua limpia.",
        category: "Salud",
        coverage: "Regional",
        contact: "info@agualimpia.org",
        website: "www.agualimpia.org",
        social: { facebook: "#", twitter: "#", linkedin: "#" },
        beneficiaries: 8900,
        campaigns_executed: 45,
        resources: "$3.2M",
        transparency: "Alta",
        verified: true,
        activeCampaigns: 8,
        totalBeneficiaries: 9200,
        location: "Medellín, Colombia",
        founded: "2015",
    },
    {
        id: 3,
        name: "Protección Animal",
        initials: "PA",
        color: "#16a34a",
        description:
            "Rescatamos, rehabilitamos y damos en adopción animales abandonados y maltratados.",
        mission: "Proteger y rescatar animales en situación de vulnerabilidad.",
        vision: "Un mundo sin animales abandonados ni maltratados.",
        category: "Animales",
        coverage: "Regional",
        contact: "ayuda@proteccionanimal.org",
        website: "www.proteccionanimal.org",
        social: { facebook: "#", twitter: "#", linkedin: "#" },
        beneficiaries: 1200,
        campaigns_executed: 32,
        resources: "$1.8M",
        transparency: "Alta",
        verified: true,
        activeCampaigns: 6,
        totalBeneficiaries: 2800,
        location: "Bogotá, Colombia",
        founded: "2012",
    },
    {
        id: 4,
        name: "Verde Futuro",
        initials: "VF",
        color: "#15803d",
        description:
            "Reforestación y conservación de ecosistemas naturales para combatir el cambio climático.",
        mission:
            "Restaurar y conservar los ecosistemas naturales de América Latina.",
        vision: "Un continente verde con ecosistemas saludables para las futuras generaciones.",
        category: "Medio Ambiente",
        coverage: "Nacional",
        contact: "contacto@verdefuturo.org",
        website: "www.verdefuturo.org",
        social: { facebook: "#", twitter: "#", linkedin: "#" },
        beneficiaries: 45000,
        campaigns_executed: 28,
        resources: "$5.1M",
        transparency: "Media",
        verified: true,
        activeCampaigns: 10,
        totalBeneficiaries: 45000,
        location: "Ciudad de México, México",
        founded: "2018",
    },
    {
        id: 5,
        name: "Salud para Todos",
        initials: "SM",
        color: "#dc2626",
        description:
            "Atención médica gratuita y prevención de enfermedades en comunidades de escasos recursos.",
        mission:
            "Democratizar el acceso a la salud en comunidades vulnerables.",
        vision: "Una región donde la salud de calidad no dependa del poder adquisitivo.",
        category: "Salud",
        coverage: "Nacional",
        contact: "contacto@saludparatodos.org",
        website: "www.saludparatodos.org",
        social: { facebook: "#", twitter: "#", linkedin: "#" },
        beneficiaries: 18500,
        campaigns_executed: 60,
        resources: "$12.3M",
        transparency: "Alta",
        verified: true,
        activeCampaigns: 15,
        totalBeneficiaries: 18500,
        location: "Lima, Perú",
        founded: "2008",
    },
    {
        id: 6,
        name: "Tecnología Inclusiva",
        initials: "TI",
        color: "#7c3aed",
        description:
            "Facilitamos acceso a tecnología y capacitación digital para personas con discapacidad.",
        mission: "Cerrar la brecha digital para personas con discapacidad.",
        vision: "Un ecosistema tecnológico verdaderamente inclusivo.",
        category: "Educación",
        coverage: "Internacional",
        contact: "hola@tecinclusiva.org",
        website: "www.tecinclusiva.org",
        social: { facebook: "#", twitter: "#", linkedin: "#" },
        beneficiaries: 3200,
        campaigns_executed: 18,
        resources: "$2.4M",
        transparency: "Media",
        verified: true,
        activeCampaigns: 5,
        totalBeneficiaries: 3200,
        location: "Santiago, Chile",
        founded: "2019",
    },
];

export const CAMPAIGNS = [
    {
        id: 1,
        title: "Educación para niños en zonas rurales",
        foundation_id: 1,
        foundation_name: "Fundación Educativa",
        category: "Educación",
        image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&q=80",
        raised: 67000,
        goal: 100000,
        donors: 342,
        deadline: "30 de Junio, 2026",
        description:
            "Este programa busca llevar educación de calidad a niños en zonas rurales que no tienen acceso a escuelas. Incluye la construcción de aulas, capacitación de maestros y entrega de material educativo.",
        updates: [
            {
                date: "15 Abr 2026",
                text: "Construimos la primera aula en la comunidad de San José",
            },
            {
                date: "1 Abr 2026",
                text: "Iniciamos capacitación con 15 nuevos maestros",
            },
        ],
        tags: ["Urgente", "Popular"],
        items: [
            {
                id: 101,
                name: "Kit escolar completo",
                category: "Material",
                price: 50,
                description:
                    "Mochila, cuadernos, lápices y materiales para un estudiante",
                impact: "Equipa a 1 estudiante por un año completo",
                image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=300&q=80",
                tag: "Popular",
                available: 45,
            },
            {
                id: 102,
                name: "Capacitación de maestro",
                category: "Capacitación",
                price: 200,
                description: "Formación pedagógica para un maestro rural",
                impact: "Capacita a 1 maestro que enseñará a 30+ niños",
                image: "https://images.unsplash.com/photo-1588072432836-e10032774350?w=300&q=80",
                tag: "Recomendado",
                available: 20,
            },
            {
                id: 103,
                name: "Construcción de aula",
                category: "Infraestructura",
                price: 5000,
                description: "Materiales para construir un aula equipada",
                impact: "Construye 1 aula para 40 estudiantes",
                image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=300&q=80",
                tag: "Urgente",
                available: 3,
            },
            {
                id: 104,
                name: "Biblioteca básica",
                category: "Material",
                price: 300,
                description: "50 libros educativos para la comunidad",
                impact: "Crea una biblioteca que beneficia a 100+ familias",
                image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&q=80",
                tag: null,
                available: 10,
            },
        ],
    },
    {
        id: 2,
        title: "Agua potable para comunidades",
        foundation_id: 2,
        foundation_name: "ONG Agua Limpia",
        category: "Salud",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
        raised: 45000,
        goal: 100000,
        donors: 189,
        deadline: "31 de Agosto, 2026",
        description:
            "Instalamos sistemas de filtración y distribución de agua potable en comunidades sin acceso a agua segura.",
        updates: [
            {
                date: "10 Abr 2026",
                text: "Instalamos el primer sistema de filtración en Villa Nueva",
            },
        ],
        tags: [],
        items: [
            {
                id: 201,
                name: "Filtro de agua familiar",
                category: "Equipamiento",
                price: 80,
                description: "Sistema de filtración para uso doméstico",
                impact: "Proporciona agua limpia a 1 familia durante 1 año",
                image: "https://images.unsplash.com/photo-1536236621141-60ed49fc6f60?w=300&q=80",
                tag: "Popular",
                available: 50,
            },
            {
                id: 202,
                name: "Kit de saneamiento",
                category: "Salud",
                price: 150,
                description: "Productos de higiene y saneamiento básico",
                impact: "Sanea el hogar de 1 familia",
                image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&q=80",
                tag: null,
                available: 30,
            },
        ],
    },
    {
        id: 3,
        title: "Refugio para animales abandonados",
        foundation_id: 3,
        foundation_name: "Protección Animal",
        category: "Animales",
        image: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
        raised: 82000,
        goal: 100000,
        donors: 521,
        deadline: "30 de Mayo, 2026",
        description:
            "Construimos y equipamos un refugio moderno para rescatar y rehabilitar animales abandonados.",
        updates: [
            { date: "20 Abr 2026", text: "Rescatamos 45 animales este mes" },
        ],
        tags: ["Popular"],
        items: [
            {
                id: 301,
                name: "Alimento mensual",
                category: "Alimentación",
                price: 25,
                description: "Alimento balanceado para un animal por un mes",
                impact: "Alimenta a 1 animal durante 1 mes",
                image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=300&q=80",
                tag: null,
                available: 100,
            },
            {
                id: 302,
                name: "Atención veterinaria",
                category: "Salud",
                price: 120,
                description: "Consulta, vacunas y tratamiento básico",
                impact: "Cubre la atención médica de 1 animal",
                image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=300&q=80",
                tag: "Urgente",
                available: 15,
            },
        ],
    },
    {
        id: 4,
        title: "Reforestación en áreas protegidas",
        foundation_id: 4,
        foundation_name: "Verde Futuro",
        category: "Medio Ambiente",
        image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&q=80",
        raised: 23000,
        goal: 100000,
        donors: 89,
        deadline: "31 de Diciembre, 2026",
        description:
            "Programa de reforestación en áreas protegidas con especies nativas para restaurar ecosistemas.",
        updates: [],
        tags: [],
        items: [
            {
                id: 401,
                name: "Árbol nativo",
                category: "Plantación",
                price: 15,
                description:
                    "Especie nativa lista para plantar en áreas protegidas",
                impact: "Planta 1 árbol nativo que captura CO2",
                image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&q=80",
                tag: null,
                available: 500,
            },
            {
                id: 402,
                name: "Kit de reforestación",
                category: "Equipamiento",
                price: 200,
                description: "Herramientas, semillas y guía de siembra",
                impact: "Planta y cuida 20 árboles por 1 año",
                image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=300&q=80",
                tag: "Recomendado",
                available: 25,
            },
        ],
    },
];

export const DONATION_ITEMS = [
    {
        id: 1,
        foundation_id: 1,
        name: "Kit escolar completo",
        category: "Educación",
        price: 25000,
        impact: "Un niño podrá estudiar todo el año",
        tag: "Popular",
        available: 45,
        active: true,
        updated: "27-04-2026",
    },
    {
        id: 2,
        foundation_id: 1,
        name: "Alimentos no perecederos",
        category: "Alimentación",
        price: 15000,
        impact: "Una familia podrá comer durante una semana",
        tag: "Urgente",
        available: 120,
        active: true,
        updated: "29-04-2026",
    },
    {
        id: 3,
        foundation_id: 1,
        name: "Vacuna para mascotas",
        category: "Animales",
        price: 35000,
        impact: "Protege a un animal durante un año",
        tag: "Recomendado",
        available: 28,
        active: true,
        updated: "24-04-2026",
    },
    {
        id: 4,
        foundation_id: 1,
        name: "Árbol nativo",
        category: "Medio Ambiente",
        price: 8000,
        impact: "Compensa 150kg de CO2 al año",
        tag: null,
        available: 0,
        active: false,
        updated: "14-03-2026",
    },
];

export const DONOR_HISTORY = [
    {
        campaign: "Educación para niños",
        item: "Kit escolar completo",
        date: "15/04/2026",
        amount: 15000,
        status: "Entregado",
    },
    {
        campaign: "Agua potable",
        item: "Filtro de agua",
        date: "08/04/2026",
        amount: 25000,
        status: "Entregado",
    },
    {
        campaign: "Refugio animal",
        item: "Alimento mensual",
        date: "01/04/2026",
        amount: 12000,
        status: "En proceso",
    },
];

export const CATEGORY_COLORS = {
    Educación: "bg-blue-100 text-blue-700",
    Salud: "bg-red-100 text-red-700",
    Animales: "bg-green-100 text-green-700",
    "Medio Ambiente": "bg-emerald-100 text-emerald-700",
    Alimentación: "bg-orange-100 text-orange-700",
    Deportes: "bg-purple-100 text-purple-700",
};

// ========================================================================================================
// TODO: Reemplazar esta data quemada por llamadas reales a supabase una vez esté corriendo el backend.
